name: Run Playit.gg Agent on macOS

on:
  push:
    branches: [ main ]

jobs:
  playit:
    name: Start Playit.gg Tunnel
    runs-on: macos-latest            # uses macOS 14 as of May 2024 :contentReference[oaicite:2]{index=2}
    steps:
      - name: Check out code
        uses: actions/checkout@v4     # get your repo’s files :contentReference[oaicite:3]{index=3}

      - name: Install Docker
        run: |
          brew install --cask docker  # install Docker on macOS runner :contentReference[oaicite:4]{index=4}
          open --background -a Docker # launch Docker daemon
          # wait for Docker to be ready
          while ! docker system info > /dev/null 2>&1; do sleep 1; done

      - name: Run Playit.gg Agent in Docker
        env:
          SECRET_KEY: ${{ secrets.PLAYIT_SECRET }}  # your Playit.gg secret :contentReference[oaicite:5]{index=5}
        run: |
          docker run --rm -d \
            --name playit-agent \
            --net=host \
            -e SECRET_KEY="${SECRET_KEY}" \
            ghcr.io/playit-cloud/playit-agent:latest
