name: Run Playit.gg Agent on macOS

on:
  push:
    branches: [ main ]

jobs:
  playit:
    name: Start Playit.gg Tunnel
    runs-on: macos-latest            # uses macOS 14 as of May 2024 :contentReference[oaicite:2]{index=2}
    steps:
      - name: Check out code
        uses: actions/checkout@v4     # get your repo’s files :contentReference[oaicite:3]{index=3}

      - name: Install Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Build playit-agent from source
        run: |
          git clone https://github.com/playit-cloud/playit-agent.git
          cd playit-agent
          cargo build --release       # produces target/release/playit-agent

      - name: Run built agent
        env:
          SECRET_KEY: ${{ secrets.PLAYIT_SECRET }}
        run: |
          ./playit-agent --secret "${SECRET_KEY}"
