name: Playit.gg Setup

on:
  push:
    branches:
      - main

jobs:
  setup-playit:
    runs-on: macos-latest
    env:
      PL: ${{ secrets.PL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Homebrew
      run: |
        if ! command -v brew &> /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi

    - name: Install Rust
      run: |
        if ! command -v cargo &> /dev/null; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . $HOME/.cargo/env
        fi

    - name: Clone Playit.gg repository
      run: git clone https://github.com/playit-cloud/playit-agent.git

    - name: Compile Playit.gg
      run: |
        cd playit-agent
        cargo build --release --verbose
        if [ $? -ne 0 ]; then
          echo "Compilation failed. Check the logs for details."
          exit 1
        fi
        ls -la target/release/  # List files in the release directory to check if the binary is there

    - name: Configure Playit.gg
      run: |
        echo "PL=$PL" > config.env
        cd playit-agent
        if [ -f ./target/release/playit ]; then
          ./target/release/playit configure --config ../config.env
        elif [ -f ./target/release/playit-cli ]; then
          ./target/release/playit-cli configure --config ../config.env
        else
          echo "No suitable binary found in the target/release directory."
          exit 1
        fi

    - name: Start Playit.gg
      run: |
        cd playit-agent
        if [ -f ./target/release/playit ]; then
          ./target/release/playit start
        elif [ -f ./target/release/playit-cli ]; then
          ./target/release/playit-cli start
        else
          echo "No suitable binary found in the target/release directory."
          exit 1
        fi
