name: Playit.gg Agent on macOS

on:
  push:
    branches: [ main ]

jobs:
  playit:
    runs-on: macos-latest          # now macOS 14 :contentReference[oaicite:5]{index=5}
    steps:
      - uses: actions/checkout@v4    # pull your code 

      - name: Install Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Build playit-agent
        run: |
          git clone https://github.com/playit-cloud/playit-agent.git
          cd playit-agent
          cargo build --release        # produces the executable :contentReference[oaicite:6]{index=6}

      - name: Run playit-agent
        env:
          PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}  # must match your secret name 
        run: |
          cd playit-agent/target/release
          chmod +x playit-agent        # ensure executable permission :contentReference[oaicite:7]{index=7}
          ./playit-agent --secret "${PLAYIT_SECRET}"
